export const typeDocumentation: Record<string, string> = {
    "Integer": "**Integer**\n\nA 32-bit whole number. It can be positive or negative. For example -1, 0 and 1.",
    "Integer64": "**Integer64**\n\nA 64-bit whole number. It can be positive or negative. For example -1LL, 0 and 123456789123.",
    "Real": "**Real**\n\nA 64-bit decimal number. It can be positive or negative. For example -1.0, 0.0 and 1.0",
    "Text": "**Text**\n\nA sequence of characters. For example \"Dog\"",
    "Vector2": "**Vector2**\n\nAn entity consisting of two Real values. If the two real values of a Vector2 are X and Y, the values in a Vector2 are often expressed as (X,Y).",
    "Vector3": "**Vector3**\n\nAn entity consisting of three Real values. If the three real values of a Vector3 are X, Y and Z, the values in a Vector3 are often expressed as (X,Y,Z).",
    "Vector4": "**Vector4**\n\nAn entity consisting of four Real values. If the four real values of a Vector3 are X, Y, Z and W, the values in a Vector4 are often expressed as (X,Y,Z,W).",
    "Matrix3": "**Matrix3**\n\nAn entity consisting of nine Real values. The values in the Matrix3 matrix are expressed as three rows and three columns.",
    "Matrix4": "**Matrix4**\n\nAn entity consisting of sixteen Real values. The values in the Matrix4 matrix are expressed as four rows and four columns.",
    "Point": "**Point**\n\nA Point is a three dimensional point consisting of x, y and z co-ordinates (x,y,z).\nA Point is a construction entity and is not stored in 12d Model models.",
    "Line": "**Line**\n\nA Line is three dimensional line joining two Points.\nA Line is a construction entity and is not stored in 12d Model models.",
    "Arc": "**Arc**\n\nAn Arc is a helix which projects onto a circle in the (x,y) plane.\nIn 12dPL an Arc is a construction entity and is not stored in 12d Model models.",
    "Spiral": "**Spiral (Transition)**\n\nAn spiral is a mathematically defined transition which when projected on to the (x,y) plane, has a continuously varying radius.\nIn 12dPL a Spiral is a construction entity and is not stored in 12d Model models.",
    "Parabola": "**Parabola**\n\nParabolas are used in the vertical geometry of an Alignment or Super Alignment.\nIn 12dPL a Parabola is a construction entity and is not stored in 12d Model models.",
    "Segment": "**Segment**\n\nA Segment is either a Point, Line, Arc, Parabola or a Spiral.\nA Segment is a construction entity and is not stored in 12d Model models.",
    "Element": "**Element**\n\nThe variable type Element is used to refer to the standard 12d Model entities that can be stored in a 12d Model models.\nElements act as handles to the data in the 12d Model database.",
    "Model": "**Model**\n\nThe variable type Model is used as a handle to refer to 12d Model models within macros.",
    "View": "**View**\n\nThe variable type View is used as a handle to refer to 12d Model views within macros.",
    "Macro_Function": "**Macro_Function**\n\nThe variable type Macro_Function or Function is used as a handle to refer to a 12d Model function within macros.",
    "Function": "**Function**\n\nThe variable type Macro_Function or Function is used as a handle to refer to a 12d Model function within macros.",
    "Undo_List": "**Undo_List**\n\nThe variable type Undo_List is a handle to a list of Undos.",
    "Uid": "**Uid**\n\nA Unique Identifier for entities in a 12d Model database.",
    "Guid": "**Guid**\n\nA Global Unique Identifier used for a 12d Model project.",
    "Attributes": "**Attributes**\n\nThe variable type Attributes is used as a handle to refer to an 12d Model attribute structure within macros.",
    "SDR_Attribute": "**SDR_Attribute**\n\nSDR_Attribute are special attributes used with the 12d Survey Data Reduction process.",
    "Blob": "**Blob**\n\nA binary object.",
    "Screen_Text": "**Screen_Text**\n\nObject for screen text operations.",
    "Textstyle_Data": "**Textstyle_Data**\n\nTextStyle_Data holds information about the text such as colour, textstyle, justification, height.",
    "Equality_Label": "**Equality_Label**\n\nEquality_Label holds information for labelling text as an Equality.",
    "Undo": "**Undo**\n\nA variable to hold information that is placed on the 12d Model Undo system.",
    "Widget": "**Widget**\n\nThe objects for building interfaces, such as menus and panels. All interface items are derived from Widget.",
    "Menu": "**Menu**\n\nAn object that holds the data for a user defined 12d Model menu.",
    "Panel": "**Panel**\n\nAn object that holds the data for a user defined 12d Model panel.",
    "Overlay_Widget": "**Overlay_Widget**\n\nUsed for formatting a panel.",
    "Vertical_Group": "**Vertical_Group**\n\nA Vertical_Group holds Widgets that will be placed vertically in a Panel.",
    "Horizontal_Group": "**Horizontal_Group**\n\nA Horizontal_Group holds Widgets that will be placed horizontally in a Panel.",
    "Widget_Pages": "**Widget_Pages**\n\nA panel can have different pages.",
    "Button": "**Button**\n\nA button on a Panel.",
    "Select_Button": "**Select_Button**\n\nA button on a Panel for selecting strings.",
    "Angle_Box": "**Angle_Box**\n\nA box on a Panel for inputting angle information.",
    "Attributes_Box": "**Attributes_Box**\n\nA box for attributes.",
    "Billboard_Box": "**Billboard_Box**\n\nA box on a Panel for selecting a billboard name.",
    "Bitmap_Fill_Box": "**Bitmap_Fill_Box**\n\nA box for bitmap fills.",
    "Chainage_Box": "**Chainage_Box**\n\nA box for chainage input.",
    "Choice_Box": "**Choice_Box**\n\nA box for making choices.",
    "Colour_Box": "**Colour_Box**\n\nA box on a Panel for selecting a colour from the pop-up list of project colours.",
    "Colour_Message_Box": "**Colour_Message_Box**\n\nA box on a Panel for writing messages to. Different background colours can be set.",
    "Date_Time_Box": "**Date_Time_Box**\n\nA box for date and time input.",
    "Directory_Box": "**Directory_Box**\n\nA box for directory selection.",
    "Draw_Box": "**Draw_Box**\n\nA box for drawing operations.",
    "File_Box": "**File_Box**\n\nA box for file selection.",
    "Function_Box": "**Function_Box**\n\nA box for function selection.",
    "Graph_Box": "**Graph_Box**\n\nA box for displaying graphs.",
    "GridCtrl_Box": "**GridCtrl_Box**\n\nA box for grid controls.",
    "HyperLink_Box": "**HyperLink_Box**\n\nA box for hyperlinks.",
    "Input_Box": "**Input_Box**\n\nA box for general input.",
    "Integer_Box": "**Integer_Box**\n\nA box for integer input.",
    "Justify_Box": "**Justify_Box**\n\nA box for text justification selection.",
    "Linestyle_Box": "**Linestyle_Box**\n\nA box on a Panel for selecting a linestyle.",
    "List_Box": "**List_Box**\n\nA box for list selection.",
    "Map_File_Box": "**Map_File_Box**\n\nA box for map file selection.",
    "Message_Box": "**Message_Box**\n\nA box on a Panel for writing messages to.",
    "Model_Box": "**Model_Box**\n\nA box on a Panel for creating or selecting a model.",
    "Name_Box": "**Name_Box**\n\nA box for name input.",
    "Named_Tick_Box": "**Named_Tick_Box**\n\nA tick box with a name.",
    "New_Select_Box": "**New_Select_Box**\n\nA new style select box.",
    "New_XYZ_Box": "**New_XYZ_Box**\n\nA new style XYZ input box.",
    "Plotter_Box": "**Plotter_Box**\n\nA box for plotter selection.",
    "Polygon_Box": "**Polygon_Box**\n\nA box for polygon operations.",
    "Real_Box": "**Real_Box**\n\nA box for real number input.",
    "Report_Box": "**Report_Box**\n\nA box for reporting.",
    "Select_Box": "**Select_Box**\n\nA box for selection.",
    "Sheet_Size_Box": "**Sheet_Size_Box**\n\nA box for sheet size selection.",
    "Source_Box": "**Source_Box**\n\nA box for source selection.",
    "Symbol_Box": "**Symbol_Box**\n\nA box for symbol selection.",
    "Tab_Box": "**Tab_Box**\n\nA box for tabs.",
    "Template_Box": "**Template_Box**\n\nA box for template selection.",
    "Text_Edit_Box": "**Text_Edit_Box**\n\nA box for editing text.",
    "Text_Style_Box": "**Text_Style_Box**\n\nA box for text style selection.",
    "Texture_Box": "**Texture_Box**\n\nA box for texture selection.",
    "Tree_Box": "**Tree_Box**\n\nA box for tree views.",
    "Tick_Box": "**Tick_Box**\n\nA tick box.",
    "Tin_Box": "**Tin_Box**\n\nA box for Tin selection.",
    "View_Box": "**View_Box**\n\nA box on a Panel for selecting a view.",
    "XYZ_Box": "**XYZ_Box**\n\nA box for XYZ coordinate input.",
    "File": "**File**\n\nA file unit.",
    "Map_File": "**Map_File**\n\nA file used for mapping element properties.",
    "Plot_Parameter_File": "**Plot_Parameter_File**\n\nA file unit.",
    "XML_Document": "**XML_Document**\n\nThe file contents are structured as an XML document.",
    "XML_Node": "**XML_Node**\n\nA node within an XML document.",
    "Connection": "**Connection**\n\nThe connection to the database.",
    "Select_Query": "**Select_Query**\n\nUsed to retrieve data from the database.",
    "Insert_Query": "**Insert_Query**\n\nUsed to add data to the database.",
    "Update_Query": "**Update_Query**\n\nUsed to update data in the database.",
    "Delete_Query": "**Delete_Query**\n\nUsed to delete data in the database.",
    "Database_Result": "**Database_Result**\n\nDatabase results.",
    "Transaction": "**Transaction**\n\nDatabase transactions.",
    "Parameter_Collection": "**Parameter_Collection**\n\nQuery the database parameters.",
    "Query_Condition": "**Query_Condition**\n\nQuery conditions.",
    "Manual_Condition": "**Manual_Condition**\n\nManual condition.",
    "Tin": "**Tin**\n\nA handle for 12d Model tins.",
    "Functions": "**Functions**\n\nA handle for 12d Model functions.",
    "Attribute_Blob": "**Attribute_Blob**\n\nA binary object.",
    "Sheet_Panel": "**Sheet_Panel**\n\nUsed for formatting a panel.",
    "Bitmap_List_Box": "**Bitmap_List_Box**\n\nA box for bitmap lists.",
    "ListCtrl_Box": "**ListCtrl_Box**\n\nA box for list control.",
    "Select_Boxes": "**Select_Boxes**\n\nMultiple select boxes.",
    "Target_Box": "**Target_Box**\n\nA box for target selection.",
    "Tree_Page": "**Tree_Page**\n\nA page in a tree box.",
    "Database_Results": "**Database_Results**\n\nDatabase results.",
    "Transactions": "**Transactions**\n\nDatabase transactions.",
    "Dynamic_Element": "**Dynamic_Element**\n\nA dynamic array of Elements.",
    "Dynamic_Text": "**Dynamic_Text**\n\nA dynamic array of Texts.",
    "Dynamic_Integer": "**Dynamic_Integer**\n\nA dynamic array of Integers.",
    "Dynamic_Integer64": "**Dynamic_Integer64**\n\nA dynamic array of 64 bits Integers.",
    "Dynamic_Real": "**Dynamic_Real**\n\nA dynamic array of Reals."
};